version: '2'
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - msa-net
      
  config-server:
    image: ekambaram/config-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8888"
    ports:
      - "8888:8888"
    networks:
      - msa-net
    depends_on:
      - rabbitmq
    volumes:
      - ./config-repo:/config-repo
      
      
      
      
      
      
networks:
  msa-net:
    driver: overlay
