version: '3'
services:
  front:
    image: ehayanis/stack-tech-ui
    ports:
      - "8081:8081"
    links:
      - back:back
    depends_on:
      - back
    networks:
      - mynet

  back:
    image: ehayanis/stack-tech
    ports:
      - "9000:9000"
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - mynet

  mongo:
    image: ehayanis/mongo
    ports:
      - "28017:28017"
      - "27017:27017"
    volumes:
      - /private/var/data:/data/db
    networks:
      - mynet

networks:
   mynet:
     driver: overlay
